[package]
name = "cs2_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
simple_logger = { workspace = true }
windows-sys = { workspace = true }
tray-icon = "0.3.0"
winit = "0.29.15"
rfd = "0.14.1"
tinyfiledialogs = "3.9.1"
